
server:
  port: 18086
spring:
  rabbitmq:
    host: 192.168.41.128
    virtual-host: /baobao
    username: guli
    password: guli
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #手动
        prefetch: 1 #能者多劳模式
        concurrency: 3 # 避免消息堆积,初始化3个线程
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #采集率
  elasticsearch:
    rest:
      uris: http://192.168.41.128:9200
  jackson: #默认排除null字段
    default-property-inclusion: non_null
  thymeleaf:
    cache: false #开发环境中不开启缓存
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug