server:
  port: 18081
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true

spring:
  rabbitmq:
    host: 192.168.41.128
    virtual-host: /baobao
    username: guli
    password: guli
    publisher-confirm-type: simple #同步
    publisher-returns: true #确认消息是否到达队列
  cloud:
    alibaba:
      seata:
        tx-service-group: gmall-tx-group