server:
  port: 18084

mybatis-plus:
  mapper-locations: classpath:mapper/ums/*.xml
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto #数据库id策略,自增
feign:
  sentinel:
    enabled: true #远程调用

